### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by mthaddon**
I've created this PR because the repo doesn't appear to have a LICENSE associated with it yet. Since "issues" aren't configured I couldn't ask about it via an issue either, so I hope it was okay to take this approach.

I'm not sure if this is the correct license to use, but seems to be what other plugins use.

Would it be possible to set up "issues" for this repository to make it easier to report issue or ask questions in the future?

### CODE REVIEW

**Review by timja — APPROVED** [review]
Looks ok, the license is at https://github.com/jenkinsci/sshd-plugin/blob/master/pom.xml#L24-L29

**Comment by jtnord** [comment]
Is this correct? There are some files licensed under ASL v2
https://github.com/jenkinsci/sshd-plugin/blob/master/src/main/java/org/jenkinsci/main/modules/cli/auth/ssh/KeyEncodeHelper.java

**Comment by timja** [comment]
Interesting some code was forked from apache mina, not sure how that is normally handled

**Comment by olamy** [comment]
looking at https://github.com/jenkinsci/sshd-plugin/blob/master/src/main/java/org/jenkinsci/main/modules/cli/auth/ssh/KeyEncodeHelper.java
it looks perfectly fine as it keep the original license

**Review by olamy — APPROVED** [review]

**Comment by daniel-beck** [comment]
> Since "issues" aren't configured

Oversight when this was made independent from core I think? https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-sshd.yml should define an issue tracker to expose a link on https://plugins.jenkins.io/sshd/

**Comment by jtnord** [comment]
> it's perfectly fine to mix licenses especially such ezy licenses as MIT and Apache

yes its fine - but shouldn't the `LICENSE` in this PR state that parts of the code are differently licenced and some are APACE, some are MIT?

**Comment by oleg-nenashev** [comment]
> it's perfectly fine to mix licenses especially such ezy licenses as MIT and Apache

Apache is more detailed than the MIT one, especially w.r.t patents ownership transfer. This is important for potentially scientific code like SSH protocol implementations. In this case I would rather re-license the entire plugin under Apache License v.2 though it may require governance meeting approval.

> Since "issues" aren't configured

It is okay to enable them here IMHO, but generally it is up to an active maintainer. Any preferences @timja @kuisathaverat @jvz 

> Oversight when this was made independent from core I think?

Yes, needs a fix in the file once we agree on the issue tracker.

**Comment by timja** [comment]
+1 to enable GitHub issues

**Review by kuisathaverat — APPROVED** [review]

**Comment by kuisathaverat** [comment]
I usually select Apache license but I do not have anything against MIT license. In the repo only a few files have license header, some are Apache and some are MIT.

**Comment by jvz** [comment]
Go ahead and use issues, yeah.

**Pull request merged**
