### PR TITLE
[JENKINS-68541] Prevent stdout/stderr stream from being closed by invoked CLI commands

### PR DESCRIPTION
**Pull request by Dohbedoh**
[JENKINS-68541](https://issues.jenkins.io/browse/JENKINS-68541)

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by Dohbedoh** [comment]
cc @jglick @Vlatombe

**Review by Vlatombe — APPROVED** [review]
LGTM

**Comment by jglick** [comment]
Workaround pending https://github.com/apache/mina-sshd/pull/214. Could leave a TODO comment reminding maintainers to remove the workaround when that is integrated, though it is trivial enough it could also just stay there.

**Review by kuisathaverat — APPROVED** [review]

**Comment by jglick** [comment]
Not sure why https://github.com/jenkinsci/sshd-plugin/runs/6526537784?check_suite_focus=true#step:4:14 failed to trigger a release. For me currently,

```console
$ gh api /repos/jenkinsci/sshd-plugin/releases | jq -e -r '.[] | select(.draft == true and .name == "next") | .body' | egrep '[💥🚨🎉🐛⚠🚀🌐👷]|:(boom|tada|construction_worker):' && echo release
## 🐛 Bug fixes
release
```

as expected. Maybe something weird going on with Release Drafter? https://github.com/jenkinsci/sshd-plugin/runs/6526537784?check_suite_focus=true#step:3:22 looks right. FYI @timja

**Comment by timja** [comment]
I re-triggered it and it's worked this time

**Pull request merged**
